news_sites:
  fox: 
    url: https://www.foxsports.com.mx
    queries:
      homepage_article_links: '.entry-title a'


  marca:
    url: https://www.marca.com/claro-mx/
    queries:
      homepage_article_links: '.flex-article__heading a'


  eluniversal:
      url: http://www.eluniversal.com.mx
      queries:
        homepage_article_links: '.field-content a'
  
  elpais:
    url: https://elpais.com/mexico/
    queries:
        homepage_article_links: '.c_t a' 