news_sites:
  foxsports: 
    url: https://www.foxsports.com.mx
    queries:
      homepage_article_links: '.entry-title a'
      article_title: '.entry-header h1'
      article_body: '.entry-content'


  marca:
    url: https://www.marca.com/claro-mx/
    queries:
      homepage_article_links: '.flex-article__heading a'
      article_title: '.ue-l-article__header-content h1'
      article_body: '.ue-c-article__body'


  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_title: '.pane-content h1'
      article_body: '.field-name-body'
  

  eltiempo:
    url: http://www.eltiempo.com
    queries:
      homepage_article_links: '.title-container a'
      article_title: '.titulo-principal-bk h1'
      article_body: '.modulos'